version: '3'
services:
  db:
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./db/volumes:/var/lib/mysql
    env_file:
      - app.env
  web:
    build:
      context: .
    command: /app/bin/bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    environment:
      RAILS_ENV: development
    env_file:
      - app.env
    depends_on:
      - db
